### ISSUE TITLE
Tailwind prose styling causes color issues with callout children elements

### ISSUE THREAD

**Issue by ryantbrown** [mintlify/components#93]
When using callout components (`<Note>` and `<Warning>`), the styling of children (`<strong>` and `<a>`) is being overridden by the prose styles.

For example, the following code:
```mdx
<Warning>
  This is a Warning callout with **bold text** and a
  [link](https://www.mintlify.com) to showcase the color issues.
</Warning>

<Note>
  This is a Note callout with **bold text** and a
  [link](https://www.mintlify.com) to showcase the color issues.
</Note>
```
produces the following:

![CleanShot 2024-10-04 at 11 48 20@2x](https://github.com/user-attachments/assets/70c4cdbb-b57b-4611-a1aa-0cd0551e2f9f)

The following css, which is prose styling, is responsible for the issue:

```css
/** <strong> **/
.prose :where(strong):not(:where([class~=not-prose],[class~=not-prose] *)) {
    color: rgb(var(--gray-900));
    font-weight: 600;
}
/** <a> **/
.prose :where(a):not(:where([class~=not-prose],[class~=not-prose] *)) {
    color: var(--tw-prose-links);
    text-decoration: none;
    font-weight: 600;
    border-bottom: 1px solid rgb(var(--primary-light));
}
```

Ideally the colors match the parent callout, for example:
![CleanShot 2024-10-04 at 12 00 27@2x](https://github.com/user-attachments/assets/9909706d-4b2b-4828-a367-7a846a2b907a)
![CleanShot 2024-10-04 at 12 01 25@2x](https://github.com/user-attachments/assets/b09b7cb7-7c38-41c3-954b-5f6e339444f3)

Because custom css is not an option until the pro plan, I am hoping this can be fixed. There are a couple solutions:

1. Remove the `prose` class from callouts (and add additional classes to get the same style, if needed)
2. Override the `prose` styles directly, `.prose :where(strong) { color: inherit; }`
3. Extend the Tailwind config and add `prose-${color}` variants to each callout type

I am not sure which would be preferred but I am happy to submit a PR if you would accept!
